//! PublrEditor — the built-in "block" editor (core admin module).
//!
//! Registers `"block"` with the editor registry in `src/editors.zig`.
//! The edit-page interface for a `"block"` content type is PublrEditor's
//! FULL HARNESS (`createEditorShell` from publr-editor/): topbar with
//! undo/redo/inserter/list-view, the block-settings sidebar, patterns
//! explorer — the same builder shell the editor demo runs. The CMS plugs
//! into the shell's host seams:
//!
//!   actions  → a primary Save button in the shell topbar (submits the
//!              standard `content.update` entry form).
//!   panels   → an "Entry" panel (toggled from the shell topbar) that ADOPTS
//!              the admin's server-rendered entry sidebar — publish/discard
//!              buttons (they target `form="entry-form"`, so they keep
//!              working from anywhere in the DOM), version history, and
//!              releases — no re-implementation.
//!
//! Storage: two projections of the same model, mirrored into hidden inputs
//! on every editor commit and saved through the standard `content.update`
//! action:
//!
//!   content          the "data" downcast — clean frontend HTML (data-pb-*
//!                    stripped, settings islands removed, data-p-* kept).
//!                    Themes emit `{entry.content}` directly; no render
//!                    override is needed.
//!   content_editing  the full wire serialization the editor reloads.
//!                    Losing it is non-fatal — the permissive upcast turns
//!                    plain `content` HTML into raw-html blocks — but typed
//!                    editability comes from this field.
//!
//! Both are produced by the editor's own downcast pipelines, so the CMS
//! never re-implements (and never drifts from) the strip semantics.
//!
//! Vendored bundle (2 files) lives in `vendor/` — GENERATED by
//! `scripts/vendor-editor.sh` (parent workspace); never edit in place.
//! Served under `/admin/editors/block/<file>` by the core asset route.
//!
//! Pre-requisites for a content type to use this editor:
//!   .editor = "block"
//!   .fields = &.{ field.Text("content", .{}), field.Text("content_editing", .{}), ... }

const std = @import("std");
const editors = @import("editors");
const cms = @import("cms");
const auth_middleware = @import("auth_middleware");
const csrf = @import("csrf");
const tpl = @import("tpl");
const views = @import("views");

const AnyWriter = std.io.AnyWriter;

// =============================================================================
// Vendored assets (embedded at compile time from vendor/)
// =============================================================================

const editor_js = @embedFile("vendor/editor.js");
const editor_css = @embedFile("vendor/editor.css");

const assets = [_]editors.Asset{
    .{ .name = "editor.js", .content = editor_js, .content_type = "application/javascript" },
    .{ .name = "editor.css", .content = editor_css, .content_type = "text/css" },
};

// =============================================================================
// Editor registration
// =============================================================================

pub const editor: editors.Editor = .{
    .id = "block",
    .bootstrap = blockBootstrap,
    .assets = &assets,
};

// The demo "article" content type lives in `plugins/publr-editor/` — a
// reference plugin showing how a content type opts into this editor
// (.editor = "block" + content/content_editing Text fields).

// =============================================================================
// Bootstrap — renders the main-pane HTML fragment for the editor page
// =============================================================================

const CONTENT_FIELD = "content";
const EDITING_FIELD = "content_editing";

// Layout takeover: the shell IS the edit interface, so break the main
// pane out of the article column (max-w-3xl + padding) and hand the
// full area to the shell, which scrolls internally. The admin metadata
// <aside> is adopted into the shell's "Entry" panel by the boot script,
// so the layout's own right rail collapses.
const takeover_css =
    \\body:has(#pbe-shell) main { display: flex !important; flex-direction: column !important; padding: 0 !important; overflow: hidden !important; }
    \\body:has(#pbe-shell) main > div { max-width: none !important; padding: 0 !important; margin: 0 !important; flex: 1; display: flex; flex-direction: column; min-height: 0; }
    \\#pbe-shell { flex: 1; min-height: 0; display: flex; flex-direction: column; }
    \\/* No theme bridging needed: the shell is self-skinned — its vendored
    \\   stylesheet scopes the editor's own dark tokens to #editor-shell,
    \\   so the admin's light/dark theme cannot recolor the editor UI
    \\   (same acceptance look as the standalone demo). */
    \\#pbe-shell #editor-shell { flex: 1; min-height: 0; }
    \\/* The adopted sidebar drops its own width/border — the host panel
    \\   provides the frame. (Class list mirrors layout_edit.zsx.) */
    \\[data-host-panel] > div > aside { width: 100% !important; border: 0 !important; }
    \\/* Canvas content baseline (v0): themes give replaced elements a
    \\   responsive default via their preflight (see jit preflight:
    \\   max-width + auto height — the width/height ATTRIBUTES then only
    \\   reserve aspect ratio). The admin ships no site CSS into the canvas
    \\   yet, so without this an uploaded photo keeps its pixel height while
    \\   max-w-full squeezes the width — a giant distorted box. Scoped to
    \\   canvas content; drop when the admin wires real theme CSS (E3). */
    \\#pbe-shell .pbe-canvas img, #pbe-shell .pbe-canvas svg, #pbe-shell .pbe-canvas video, #pbe-shell .pbe-canvas canvas { max-width: 100%; height: auto; }
;

const boot_js =
    \\// Load editor assets via fetch() so iOS-webview's fetch shim (which
    \\// routes /admin/* through the WASM CMS) picks them up — same pattern
    \\// and rationale as the gutenberg plugin.
    \\//
    \\// SPA-navigation re-entry: head scripts persist across the iOS demo's
    \\// body-innerHTML navigations, so window.Publr.Editor may already
    \\// exist. Feature-detect and skip injection; block registration is
    \\// likewise guarded (registerBlock throws on duplicates).
    \\(async function(){
    \\  var base = '/admin/editors/block/';
    \\  async function loadText(path){
    \\    var r = await fetch(base + path);
    \\    if (!r.ok) throw new Error('failed to load ' + path + ' (' + r.status + ')');
    \\    return await r.text();
    \\  }
    \\  function injectStyle(text, id){
    \\    if (id && document.getElementById(id)) return;
    \\    var s = document.createElement('style');
    \\    if (id) s.id = id;
    \\    s.textContent = text;
    \\    document.head.appendChild(s);
    \\  }
    \\  function injectScript(text){
    \\    var s = document.createElement('script');
    \\    s.textContent = text;
    \\    document.head.appendChild(s);
    \\  }
    \\  var loaded = window.Publr && window.Publr.Editor && typeof window.Publr.Editor.createEditorShell === 'function';
    \\  if (!loaded) {
    \\    try {
    \\      injectStyle(await loadText('editor.css'), 'pbe-editor-css');
    \\      injectScript(await loadText('editor.js'));
    \\    } catch (e) {
    \\      console.error('Failed to load PublrEditor:', e);
    \\      return;
    \\    }
    \\  }
    \\  var E = window.Publr.Editor;
    \\
    \\  // Register the core set once per page lifetime.
    \\  if (!E.getBlockType('paragraph')) {
    \\    E.registerCoreBlocks();
    \\    E.registerCorePatterns();
    \\  }
    \\
    \\  var contentInput = document.getElementById('pbe-content-value');
    \\  var editingInput = document.getElementById('pbe-editing-value');
    \\  var form = document.getElementById('entry-form');
    \\
    \\  // Media adapter — the editor's upload/browse seam, pointed at the CMS
    \\  // media library. upload() posts the standard multipart action form
    \\  // (media.upload_json returns the stored record as JSON; _csrf rides as
    \\  // a multipart field). browse() opens the admin's media picker (the
    \\  // PublrJS store in /static/scripts/media-picker.js) via
    \\  // window.PublrAdmin.pickMedia — looked up lazily because that module
    \\  // is deferred and may load after this inline script runs.
    \\  function mediaValueFrom(m){
    \\    return {
    \\      src: m.url,
    \\      alt: m.alt_text || undefined,
    \\      width: m.width || undefined,
    \\      height: m.height || undefined,
    \\      id: m.id,
    \\    };
    \\  }
    \\  var media = {
    \\    upload: async function(file){
    \\      var fd = new FormData();
    \\      fd.append('action', 'media.upload_json');
    \\      var csrfInput = form.querySelector('input[name="_csrf"]');
    \\      if (csrfInput) fd.append('_csrf', csrfInput.value);
    \\      fd.append('file', file, file.name);
    \\      var r = await fetch('/admin/action', { method: 'POST', body: fd });
    \\      var m = null;
    \\      try { m = await r.json(); } catch (e) { /* non-JSON error page */ }
    \\      if (!r.ok || !m || m.error) {
    \\        throw new Error('media upload failed: ' + ((m && m.error) || r.status));
    \\      }
    \\      return mediaValueFrom(m);
    \\    },
    \\    browse: async function(){
    \\      if (!(window.PublrAdmin && window.PublrAdmin.pickMedia)) return null;
    \\      var m = await window.PublrAdmin.pickMedia({});
    \\      return m ? mediaValueFrom(m) : null;
    \\    },
    \\  };
    \\
    \\  // Mirror both serializations into the hidden inputs on every
    \\  // committed change (onChange fires on a microtask after the model
    \\  // settles — no polling). The synthetic input event feeds the entry-editor
    \\  // dirty-detection so Publish enables.
    \\  function sync(editor){
    \\    editingInput.value = editor.serialize();
    \\    contentInput.value = editor.serialize({ pipeline: 'data' });
    \\    contentInput.dispatchEvent(new Event('input', { bubbles: true }));
    \\  }
    \\
    \\  var shell = await E.createEditorShell({
    \\    container: document.getElementById('pbe-shell'),
    \\    // Seed from the full wire serialization; fall back to the clean
    \\    // frontend HTML (permissive upcast keeps it as raw-html blocks).
    \\    // A brand-new entry gets one empty paragraph so the placeholder
    \\    // ghost + caret are live immediately (loadHtml resets history,
    \\    // so the seed is not a dirty edit).
    \\    content: editingInput.value || contentInput.value ||
    \\      '<p data-pb-block="paragraph" data-pb-rich="body"></p>',
    \\    placeholder: 'Start writing, or type / to choose a block',
    \\    media: media, // the CMS media library (upload + picker), defined above
    \\    // The shell follows the admin theme (html.dark): initial state here,
    \\    // live sync via shell.setAppearance below.
    \\    appearance: document.documentElement.classList.contains('dark') ? 'dark' : 'light',
    \\    onChange: sync,
    \\    // CMS-driven preview: POST the current (possibly unsaved) content to
    \\    // the content.preview action, which renders it through the site's
    \\    // real CSS pipeline (theme.css + runtime JIT). target=_blank keeps
    \\    // the editor page intact; nothing is written to the entry.
    \\    preview: function(editor){
    \\      var f = document.createElement('form');
    \\      f.method = 'POST';
    \\      f.action = '/admin/action';
    \\      f.target = '_blank';
    \\      function add(n, v){
    \\        var i = document.createElement('input');
    \\        i.type = 'hidden'; i.name = n; i.value = v;
    \\        f.appendChild(i);
    \\      }
    \\      add('action', 'content.preview');
    \\      var csrfInput = form.querySelector('input[name="_csrf"]');
    \\      if (csrfInput) add('_csrf', csrfInput.value);
    \\      add('content', editor.serialize({ pipeline: 'data' }));
    \\      document.body.appendChild(f);
    \\      f.submit();
    \\      f.remove();
    \\    },
    \\    actions: [
    \\      { id: 'save', label: 'Save', primary: true, title: 'Save (content.update)',
    \\        onClick: function(){ form.requestSubmit(); } },
    \\    ],
    \\    panels: [
    \\      { id: 'entry', title: 'Entry',
    \\        icon: '<svg class="h-6 w-6" viewBox="0 0 24 24" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="8"/><path d="M12 8.25V12l2.5 2.5"/></g></svg>',
    \\        mount: function(el){
    \\          // Adopt the admin's server-rendered entry sidebar wholesale:
    \\          // status, publish/discard, sidebar fields, version history,
    \\          // releases. Everything keeps working — the entry-editor store delegates
    \\          // events at the document level and the buttons target
    \\          // form="entry-form".
    \\          var aside = document.querySelector('.admin-card main + aside');
    \\          if (aside) el.appendChild(aside);
    \\        } },
    \\    ],
    \\  });
    \\
    \\  // Console handle, same convention as the demo shell.
    \\  window.Publr.editor = shell.editor;
    \\
    \\  // Keep the shell appearance in lockstep with the admin theme toggle
    \\  // (layout_edit's toggleTheme flips `dark` on <html>).
    \\  new MutationObserver(function(){
    \\    shell.setAppearance(document.documentElement.classList.contains('dark') ? 'dark' : 'light');
    \\  }).observe(document.documentElement, { attributes: true, attributeFilter: ['class'] });
    \\
    \\  // Belt-and-braces: final sync before submit (capture phase, before
    \\  // the entry-editor store reads the inputs).
    \\  form.addEventListener('submit', function(){ sync(shell.editor); }, true);
    \\})();
;

fn blockBootstrap(args: editors.BootstrapArgs, w: AnyWriter) anyerror!void {
    const allocator = args.ctx.allocator;
    const db = if (auth_middleware.auth) |a| a.db else return;

    var entry = (cms.query.getEntry(allocator, db, args.def.type_id, args.entry_id) catch return) orelse return;
    defer entry.deinit(allocator);

    // The markup lives in the ZSX view (epic #191); attribute values are
    // escaped by the ZSX emitter, so the raw field texts pass through as-is.
    try w.writeAll(tpl.render(views.admin.content.block_editor.BlockEditorBootstrap, .{.{
        .type_id = args.def.type_id,
        .entry_id = args.entry_id,
        .entry_status = entry.status,
        .csrf_token = csrf.ensureToken(args.ctx),
        .content = entry.data.getText(CONTENT_FIELD) orelse "",
        .content_editing = entry.data.getText(EDITING_FIELD) orelse "",
        .takeover_css = takeover_css,
        .boot_js = boot_js,
    }}));
}

// Tests exercise the editor via the registry's public interface and live in
// `src/tests/editors_tests.zig` — module files aren't on main.zig's
// transitive import graph, so inline tests here wouldn't be discovered.
